# Generated by Django 4.0.4 on 2022-06-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tag_order_customer_order_product_order_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(to='accounts.tag'),
        ),
    ]
